
// Everything that can possibly pop up a dialog screen

var dialogue =
[
	{id: 0,
     dialog: "Finally, I've arrived at the airport!\nNow all I have to do is find out how to get to my hotel.", speak: true,
	 connection: undefined},
	 {id: 1,
     dialog: "Excuse me! I need to get to the Holiday Inn in the city. How can I get there fast?", speak: true,
	 connection: 2},
	 {id: 2,
     dialog: "Sorry, je no speak Anglais.", speak: true,
	 connection: undefined},
	 {id: 3,
     dialog: "... eh? Gracias, no problemo.", speak: true,
	 connection: undefined},
	 {id: 0,
     dialog: "Excuse me--", speak: true,
	 connection: undefined},
	 {id: 0,
     dialog: "Sorry! I'm in a hurry!", speak: true,
	 connection: undefined},
	 {id: 0,
     dialog: "What an unfriendly person...", speak:false,
	 connection: undefined},
	 	{id: 0,
     dialog: "I'm not local, sorry. Maybe ask that guy over there?", speak: true,
	 connection: undefined},
	 	{id: 0,
     dialog: "Hmmph, thanks anyway.", speak: true,
	 connection: undefined},
	 	{id: 0,
     dialog: "I think you have to take the bus. The Holiday Inn should be near the Heartbleed Hospital, although I don't know which bus goes by it...", speak: true,
	 connection: undefined},
	 	{id: 0,
     dialog: "Damn, where can I find bus schedules...", speak:false,
	 connection: undefined},
	 {id: 0,
     dialog: "Thank you.", speak:true,
	 connection: undefined},
	  {id: 0,
     dialog: "You are a lovely beauty, like one of my porcelain dolls~", speak:true,
	 connection: undefined},
	  {id: 0,
     dialog: "Excuse me again, I am searching for the bus schedules, have you seen them by any chance?", speak:true,
	 connection: undefined},
	  {id: 0,
     dialog: "I think there's no point in asking him.", speak:false,
	 connection: undefined},
	  {id: 0,
     dialog: "Didn't you hear me, I'm in a hurry!", speak:true,
	 connection: undefined},
	  {id: 0,
     dialog: "Hmm... Yes I think I've seen those somewhere in the hall... try near the restrooms or entrance?", speak:true,
	 connection: undefined},
	  {id: 0,
     dialog: "That woman said the hotel is near Heartbleed Hospital...", speak:false,
	 connection: undefined},
	  {id: 0,
     dialog: "No, this one doesn't seem right.", speak:false,
	 connection: undefined},
	  {id: 0,
     dialog: "There it is - line 86! ... Aaaand the last one today is already gone. Damn this!", speak:false,
	 connection: undefined},
	  {id: 0,
     dialog: "And thus I took a cab, and decided to stop by Jenny's house directly.~", speak:false,
	 connection: undefined},
	  {id: 0,
     dialog: "So let's see if she's home <3", speak:false,
	 connection: undefined},
	  {id: 0,
     dialog: "Blinds are closed and no lights - maybe she's sleeping already.", speak:false,
	 connection: undefined},
	  {id: 0,
     dialog: "Rrrrrring. RRRRRRRRRRRRRRing!", speak:true,
	 connection: undefined},
	 {id: 0,
	 dialog: "Ring ring ring ring ring banana phone…", speak:false,
	 connection: undefined},
	 	 {id: 0,
	 dialog: "RRRRRRRRRRRRRRRRRRRRRRRRRing!", speak:true,
	 connection: undefined},
	 	 	 {id: 0,
	 dialog: "This won't open.", speak:false,
	 connection: undefined},
	 {id: 0,
	 dialog: "Closed tight. No chance.", speak:false,
	 connection: undefined},
	 {id: 0,
	 dialog: "God dammit!", speak:false,
	 connection: undefined},
	 {id: 0,
	 dialog: "Ah, the blinds aren't shut. I may be able to break in here.", speak:false,
	 connection: undefined},
	 {id: 0,
	 dialog: "This won't open.", speak:false,
	 connection: undefined},
	 {id: 0,
	 dialog: "Maybe this one will work!", speak:false,
	 connection: undefined},
		 {id: 0,
	 dialog: "Let me pick this up!", speak:false,
	 connection: undefined}, 
	 	 {id: 0,
	 dialog: "I'll try this.", speak:false,
	 connection: undefined},
	 {id: 0,
	 dialog: "Dammit, this isn't working.", speak:false,
	 connection: undefined},
	 
	 {id: 0,
	 dialog: "Well, this was a bad idea...", speak:false,
	 connection: undefined},
	 
	 {id: 0,
	 dialog: "Why did I bother picking this up?", speak:false,
	 connection: undefined},
	 	 {id: 0,
	 dialog: "What about this? Let's try.", speak:false,
	 connection: undefined},
	 	 {id: 0,
	 dialog: "Finally....", speak:true,
	 connection: undefined},
	 
	 /* inside the house */
	 
	 	 {id: 0,
	 dialog: "A clean sink with a tidy cabinet.", speak:false,
	 connection: undefined},
	 	 {id: 0,
	 dialog: "I need to shave.", speak:false,
	 connection: undefined},
	 
	 	 {id: 0,
	 dialog: "It's dark down there. I don't think Jenny is in the basement.", speak:false,
	 connection: undefined},
	 	 {id: 0,
	 dialog: "She has cable connected to the TV! Can't find the remote, though...", speak:false,
	 connection: undefined},
	 	 {id: 0,
	 dialog: "Not much in the fridge... cute photos of her dogs on the door, though.", speak:false,
	 connection: undefined},
	 	 {id: 0,
	 dialog: "It's been a while since they passed away.", speak:false,
	 connection: undefined},
	 
];